# Generated by Django 5.0.6 on 2024-05-13 21:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("year", models.IntegerField()),
                ("country", models.CharField(max_length=100)),
                ("director", models.CharField(max_length=100)),
                ("cast", models.CharField(max_length=600)),
                ("rate", models.CharField(max_length=10)),
                ("category", models.CharField(max_length=100)),
                ("genre", models.CharField(max_length=100)),
                ("duration", models.BigIntegerField()),
                ("image", models.CharField(max_length=100)),
                ("plot", models.TextField()),
            ],
        ),
    ]
