# Generated by Django 5.0.4 on 2024-05-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0002_remove_movie_category_remove_movie_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="rate",
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
    ]
