# Generated by Django 5.0.6 on 2024-05-14 07:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="category",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="image",
        ),
    ]
